version: "3.7"
services:
  db:
    image: postgres:13.3
    restart: always
    env_file: .env
    expose:
      - "${POSTGRES_PORT}"
  telegram_bot:
    build: .
    depends_on:
      - db
    restart: always
    env_file: .env
    command: bash -c "alembic upgrade head && python run_bot.py"
    expose:
      - "49151"